resources:
- repo: self

jobs:
- job: macos_x64
  strategy:
    matrix:
      RELEASE:
        Configuration: release
  displayName: 'macOS x64'
  timeoutInMinutes: 60
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - checkout: self 
    fetchDepth: 1
  - task: UseDotNet@1
    displayName: 'Install .NET 5 SDK'
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
      includePreviewVersions: true
  - bash: dotnet test -v normal --logger trx
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunTitle: "MacOS 10.14"
      platform: "MacOS 10.14"
      testRunner: VSTest
      testResultsFiles: '**/*.trx'